name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest  # or use windows-latest if on Windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7  # Using Ruby 2.7

    - name: Install Bundler
      run: gem install bundler -v 2.4.22  # Install Bundler 2.4.22 for Ruby 2.7

    - name: Install dependencies
      run: bundle install

    - name: Build the Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: _site
        token: ${{ secrets.GITHUB_TOKEN }}
